# Generated by Django 3.1.6 on 2021-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('student', 'student'), ('classroom_assistant', 'classroom assistant'), ('open_source', 'open source'), ('no_offers', 'no special offers')], default='no_offers', max_length=20)),
                ('user_type', models.CharField(choices=[('individual', 'individual'), ('business', 'business')], default='individual', max_length=15)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(choices=[('Poland', 'Poland'), ('USA', 'USA'), ('Estonia', 'ESTONIA')], default='Poland', max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.UniqueConstraint(fields=('offer_type', 'user_type'), name='unique pricing'),
        ),
    ]
