# Generated by Django 3.1.6 on 2021-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='offer_type',
            field=models.CharField(choices=[('student', 'student'), ('classroom_assistant', 'classroom assistant'), ('open_source', 'open source'), ('no_offers', 'no special offers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('business', 'business')], max_length=15),
        ),
    ]
