# Generated by Django 3.1.5 on 2021-01-19 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('user_type', models.CharField(choices=[('individual', 'individual'), ('business', 'business')], max_length=56)),
                ('billing_type', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=56)),
                ('special_offers', models.CharField(choices=[('student', 'student'), ('classroom_assistant', 'classroom assistant'), ('open_source', 'open source'), ('no_offers', 'no special offers')], max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
