# Generated by Django 3.1.6 on 2021-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210131_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
