# Generated by Django 3.1.6 on 2021-02-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210204_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
