# Generated by Django 3.1.5 on 2021-01-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('paid', 'paid'), ('in progress', 'in progress'), ('not paid', 'not paid'), ('declined', 'declined')], default='in progress', max_length=50),
        ),
    ]
