# Generated by Django 3.1.5 on 2021-01-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210127_1140'),
        ('orders', '0002_auto_20210127_1201'),
    ]

    operations = [
    ]
