# Generated by Django 3.1.5 on 2021-01-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210131_1420'),
        ('orders', '0003_merge_20210127_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='subscriptions.subscription'),
        ),
    ]
